-- MySQL Script generated by MySQL Workbench
-- Wed Jan 14 09:54:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PixelTraderInc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PixelTraderInc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PixelTraderInc` DEFAULT CHARACTER SET utf8 ;
USE `PixelTraderInc` ;

-- -----------------------------------------------------
-- Table `PixelTraderInc`.`Etat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PixelTraderInc`.`Etat` (
  `idEtat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`idEtat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PixelTraderInc`.`Prix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PixelTraderInc`.`Prix` (
  `idPrix` INT NOT NULL AUTO_INCREMENT,
  `valeurEstimé` FLOAT NOT NULL,
  PRIMARY KEY (`idPrix`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PixelTraderInc`.`Emplacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PixelTraderInc`.`Emplacement` (
  `idEmplacement` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`idEmplacement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PixelTraderInc`.`Plateforme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PixelTraderInc`.`Plateforme` (
  `idPlateforme` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`idPlateforme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PixelTraderInc`.`Jeux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PixelTraderInc`.`Jeux` (
  `idJeu` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(245) NOT NULL,
  `idPlatforme` INT NOT NULL,
  `anneesortie` INT NOT NULL,
  `idEtat` INT NOT NULL,
  `idEmplacement` INT NOT NULL,
  `idPrix` INT NOT NULL,
  PRIMARY KEY (`idJeu`),
  INDEX `fk_Jeux_Etat1_idx` (`idEtat` ASC) VISIBLE,
  INDEX `fk_Jeux_Prix1_idx` (`idPrix` ASC) VISIBLE,
  INDEX `fk_Jeux_Emplacement1_idx` (`idEmplacement` ASC) VISIBLE,
  INDEX `fk_Jeux_Plateforme1_idx` (`idPlatforme` ASC) VISIBLE,
  CONSTRAINT `fk_Jeux_Etat1`
    FOREIGN KEY (`idEtat`)
    REFERENCES `PixelTraderInc`.`Etat` (`idEtat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jeux_Prix1`
    FOREIGN KEY (`idPrix`)
    REFERENCES `PixelTraderInc`.`Prix` (`idPrix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jeux_Emplacement1`
    FOREIGN KEY (`idEmplacement`)
    REFERENCES `PixelTraderInc`.`Emplacement` (`idEmplacement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jeux_Plateforme1`
    FOREIGN KEY (`idPlatforme`)
    REFERENCES `PixelTraderInc`.`Plateforme` (`idPlateforme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PixelTraderInc`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PixelTraderInc`.`Stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `idJeu` INT NOT NULL,
  `disponibilité` INT NOT NULL,
  `prixAchat` FLOAT NOT NULL,
  `idPrix` INT NOT NULL,
  PRIMARY KEY (`idStock`),
  INDEX `fk_Stock_Jeux_idx` (`idJeu` ASC) VISIBLE,
  INDEX `fk_Stock_Prix1_idx` (`idPrix` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Jeux`
    FOREIGN KEY (`idJeu`)
    REFERENCES `PixelTraderInc`.`Jeux` (`idJeu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_Prix1`
    FOREIGN KEY (`idPrix`)
    REFERENCES `PixelTraderInc`.`Prix` (`idPrix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
